/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./src/components/common/AppAvatar.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLoading: typeof import('./src/components/common/AppLoading.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    AppNavBar: typeof import('./src/components/common/AppNavBar.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    MomentCard: typeof import('./src/components/moment/MomentCard.vue')['default']
    WdActionSheet: typeof import('wot-design-uni/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['default']
    WdEmpty: typeof import('wot-design-uni/components/wd-empty/wd-empty.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdImg: typeof import('wot-design-uni/components/wd-img/wd-img.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdSearch: typeof import('wot-design-uni/components/wd-search/wd-search.vue')['default']
    WdSwipeAction: typeof import('wot-design-uni/components/wd-swipe-action/wd-swipe-action.vue')['default']
    WdSwitch: typeof import('wot-design-uni/components/wd-switch/wd-switch.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
