/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./src/components/common/AppAvatar.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLoading: typeof import('./src/components/common/AppLoading.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    AppNavBar: typeof import('./src/components/common/AppNavBar.vue')['default']
    AppTabBar: typeof import('./src/components/common/AppTabBar.vue')['default']
    CallWindow: typeof import('./src/components/call/CallWindow.vue')['default']
    GroupCallBanner: typeof import('./src/components/call/GroupCallBanner.vue')['default']
    GroupCallIncoming: typeof import('./src/components/call/GroupCallIncoming.vue')['default']
    GroupCallModal: typeof import('./src/components/call/GroupCallModal.vue')['default']
    GroupCallWindow: typeof import('./src/components/call/GroupCallWindow.vue')['default']
    ImagePreview: typeof import('./src/components/common/ImagePreview.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    MentionPicker: typeof import('./src/components/chat/MentionPicker.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    MomentCard: typeof import('./src/components/moment/MomentCard.vue')['default']
    MomentCommentInput: typeof import('./src/components/moment/MomentCommentInput.vue')['default']
    MomentCommentList: typeof import('./src/components/moment/MomentCommentList.vue')['default']
    MomentNotificationPanel: typeof import('./src/components/moment/MomentNotificationPanel.vue')['default']
    SelectContactsModal: typeof import('./src/components/chat/SelectContactsModal.vue')['default']
    UserInfoCard: typeof import('./src/components/common/UserInfoCard.vue')['default']
    UserMomentsModal: typeof import('./src/components/moment/UserMomentsModal.vue')['default']
    VideoPlayer: typeof import('./src/components/common/VideoPlayer.vue')['default']
    VisibilitySelector: typeof import('./src/components/moment/VisibilitySelector.vue')['default']
  }
}
